### PR TITLE
Request to merge the Feature branch with Main

### PR DESCRIPTION
**Pull request by sun1lkumar**
This project's goal is to clone a replica of the newsweek.com website using bootstrap.

### CODE REVIEW

**Comment by mimipeshy** [comment]
## STATUS: CHANGES REQUESTED 🔴 ♻️ 

Hello team @DsunilK and @kimothokamau 👋  👋 , you guys did so well in this project, it almost looks like the real one 👏 👏 .
However, before we can mark it as `complete` let's make a few more changes. 

- [x] The live demo link on the README file throws a 404 status not found error. Kindly work on it. You can use the link  [gh-pages](https://docs.github.com/en/free-pro-team@latest/github/working-with-github-pages/creating-a-github-pages-site) if you are looking for a hosting solution.

- [x] On the navbar, change the color of the subscribe button to look like the original page. You can use the extension[color picker](https://chrome.google.com/webstore/detail/color-picker/gffjdohanhmkfbpnjlnmaeabfhghpilo) to help in the accuracy of the color

- [x] When I hover over the menu links, the text-color should change to red. In the clone, the color remains the same but with underlines, kindly work on that.

**Changes to be made on the Medium version (tablet view)**
- [x] The debate and the opinion section should take the maximum width of the page. ([link to page](https://www.newsweek.com/))

Original
debate

Clone
clo

- [x] The form `start your day with our top 5 articles` , which is just above the `in the magazine section`  is centered on te original page ([link to page](https://www.newsweek.com/)). Kindly work on this too.

- [x] The sections US, WORLD  BUSINESS etc, has a menu that appears on the right side of the page. ([link to page](https://www.newsweek.com/)). In the clone, the menu appears at the bottom. Kindly work on this

Original
us

Clone
clon

- [x] Lets make the subscribe and newsletter section look like the original one ([link to page](https://www.newsweek.com/))
 Original
sub
Clone
clo

**Changes to be made on the small version (mobile view)**

- [x] Remove the padding around the page, elements should occupy the max-width as the original page([link to page](https://www.newsweek.com/))

Original 
or

Clone
clo

- [x] Check on the color of the icon representing a user. ([link to page](https://www.newsweek.com/))
Original
or
Clone
clo



- [x] The debate section should appear after ` Featured Stories` and not after `More Stories` as appears on the clone page. ([link to page](https://www.newsweek.com/))

- [x] Add more margin between `In the magazine section` and the article above it
co

- [x] Lets work on the `Subscribe` and `Newsletter` section. Make it look like the original one ([link to page](https://www.newsweek.com/))

Thats all 😄 , kindly submit another review when you are done.

Regards
Peris Ndanu
Feel free to slack me if you have any questions.

**Comment by kimothokamau** [comment]
Hello TSE, we have made the required changes. Please review our code again.

**Review by arslanbisharat — APPROVED** [review]
# Approved :smile: 

Hello Developer :wave:

I just reviewed your project and I am very happy to inform you that your project is approved.
Congratulations on achieving this milestone in your career. :clap:



_I am looking forward to seeing your next project._

Stay safe and give me a smile 😇

### Happy Coding
------------------------------------------------------------------------------------------------
**Regards,
Arslan Bisharat
slack: arslanbisharat**

**Comment by SunilDevalla** [comment]
> # Approved 😄
> Hello Developer 👋
> 
> I just reviewed your project and I am very happy to inform you that your project is approved.
> Congratulations on achieving this milestone in your career. 👏
> 
> _I am looking forward to seeing your next project._
> 
> Stay safe and give me a smile 😇
> 
> ### Happy Coding
> **Regards, Arslan Bisharat slack: arslanbisharat**

Thank you Arslan Bisharat

**Pull request merged**
